apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-express-app
  template:
    metadata:
      labels:
        app: node-express-app
    spec:
      containers:
        - name: node-express-app
          image: your-dockerhub-username/node-express-app:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-express-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: node-express-app
